# Generated by Django 5.2.5 on 2025-09-14 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_avatar_user_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qrcode',
            old_name='code_data',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='owner',
        ),
        migrations.AddField(
            model_name='qrcode',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='qrcodes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('members', models.ManyToManyField(related_name='user_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
