# Generated by Django 5.2.5 on 2025-10-05 18:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_code_data_qrcode_data_remove_qrcode_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='events', to='api.usergroup'),
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='events_participating', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
