# Generated by Django 5.2.5 on 2026-07-13 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_shift_shiftsignup_shift_participants_checkin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='shiftsignup',
            unique_together={('shift', 'user')},
        ),
        migrations.AddField(
            model_name='event',
            name='checkin_mode',
            field=models.CharField(choices=[('personal_qr', "Personal QR — an admin scans each volunteer's own badge"), ('event_qr', 'Event QR — volunteers scan one shared code themselves')], default='event_qr', max_length=20),
        ),
        migrations.AddField(
            model_name='shift',
            name='criticality',
            field=models.CharField(choices=[('normal', 'Normal'), ('critical', 'Critical — requires relevant experience')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='shiftsignup',
            name='experience_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shiftsignup',
            name='has_relevant_experience',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='experience_notes',
            field=models.TextField(blank=True, help_text='Freeform background: previous experience, education, certifications.'),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_confirmed', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.event')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.shift')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-confirmed_at'],
                'unique_together': {('event', 'user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='EventCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('checked_in_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='api.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_arrivals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-checked_in_at'],
                'unique_together': {('event', 'user', 'date')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='users', to='api.skill'),
        ),
        migrations.DeleteModel(
            name='CheckIn',
        ),
    ]
