# Generated by Django 5.2.5 on 2026-07-13 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_skill_alter_shiftsignup_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='event_group_invite',
        ),
        migrations.AlterUniqueTogether(
            name='eventinvite',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='eventinvite',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventinvite',
            name='invited_by',
        ),
        migrations.RemoveField(
            model_name='eventinvite',
            name='invitee',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='event_invite',
        ),
        migrations.AlterUniqueTogether(
            name='groupinvite',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='groupinvite',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupinvite',
            name='invited_by',
        ),
        migrations.RemoveField(
            model_name='groupinvite',
            name='invitee',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='group_invite',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='members',
        ),
        migrations.RemoveField(
            model_name='event',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='event',
            name='auto_approve',
        ),
        migrations.RemoveField(
            model_name='event',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='auto_approve',
        ),
        migrations.DeleteModel(
            name='EventGroupInvite',
        ),
        migrations.DeleteModel(
            name='EventInvite',
        ),
        migrations.DeleteModel(
            name='GroupInvite',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='UserGroup',
        ),
    ]
