# Generated by Django 5.2.5 on 2026-07-13 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_notification_event_group_invite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='leaders',
            field=models.ManyToManyField(blank=True, help_text='Oppgave leaders: can edit this shift and assign its pool candidates.', related_name='shifts_led', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shift',
            name='min_capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum volunteers needed. Informational only — used for understaffing alerts/metrics, not enforced at signup.', null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum volunteers. Blank = no limit.', null=True),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('superadmin', 'Superadmin'), ('checkin_staff', 'Check-in staff')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='api.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('event', 'user', 'role')},
            },
        ),
    ]
