# Generated by Django 5.2.5 on 2026-07-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_shift_leaders_shift_min_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('superadmin', 'Superadmin'), ('checkin_staff', 'Check-in staff')], max_length=20),
        ),
    ]
