# Generated by Django 5.2.5 on 2026-07-14 12:40

from django.db import migrations, models


def rename_superadmin_to_admin(apps, schema_editor):
    Membership = apps.get_model('api', 'Membership')
    Membership.objects.filter(role='superadmin').update(role='admin')


def rename_admin_to_superadmin(apps, schema_editor):
    Membership = apps.get_model('api', 'Membership')
    Membership.objects.filter(role='admin').update(role='superadmin')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_membership_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Private notes for admins only, e.g. behavior from previous years. Never exposed to the volunteer themselves -- see UserAdminNoteSerializer.'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('checkin_staff', 'Check-in staff')], max_length=20),
        ),
        migrations.RunPython(rename_superadmin_to_admin, rename_admin_to_superadmin),
    ]
