# Generated by Django 5.2.5 on 2026-07-14 18:49

from django.db import migrations, models


def activate_most_recent_event(apps, schema_editor):
    """Before this migration, public_event/the app picked the event by
    "latest by id" -- activate that same one so existing deployments don't
    suddenly show "no event configured" once is_active starts being used."""

    Event = apps.get_model('api', 'Event')
    latest = Event.objects.order_by('-id').first()
    if latest:
        Event.objects.filter(pk=latest.pk).update(is_active=True)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_event_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=False, help_text='The one event the public website/app show. Only one event is active at a time.'),
        ),
        migrations.RunPython(activate_most_recent_event, noop_reverse),
    ]
