# Generated by Django 5.2.5 on 2026-07-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_event_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='signup_closes_at',
            field=models.DateTimeField(blank=True, help_text='Volunteer registration is closed after this time. Blank = no upper bound.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='signup_opens_at',
            field=models.DateTimeField(blank=True, help_text='Volunteer registration is closed before this time. Blank = no lower bound.', null=True),
        ),
    ]
