# Generated by Django 5.2.5 on 2026-07-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_user_options_user_unique_user_email_ci'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='phase',
            field=models.CharField(blank=True, choices=[('setup', 'Forberedelse'), ('guest', 'Gjester til stede'), ('teardown', 'Rydding')], max_length=10),
        ),
        migrations.AddField(
            model_name='skill',
            name='allowed_in_guest',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='allowed_in_setup',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='allowed_in_teardown',
            field=models.BooleanField(default=True),
        ),
    ]
