# Generated by Django 5.2.5 on 2026-07-15 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_shift_phase_skill_allowed_in_guest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_conflicts', to='api.event')),
                ('shift_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_as_a', to='api.shift')),
                ('shift_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_as_b', to='api.shift')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
