# Generated by Django 5.2.5 on 2026-07-16 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_shiftconflict'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='phase',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='allowed_in_guest',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='allowed_in_setup',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='allowed_in_teardown',
        ),
        migrations.CreateModel(
            name='OppgaveSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Maximum volunteers for this oppgave on this vakt. Blank = no limit.', null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oppgave_slots', to='api.event')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oppgave_slots', to='api.shift')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oppgave_slots', to='api.skill')),
            ],
            options={
                'ordering': ['shift__date', 'shift__start_time', 'skill__name'],
                'unique_together': {('shift', 'skill')},
            },
        ),
    ]
