# Generated by Django 5.2.5 on 2026-07-16 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    # default=1/preserve_default=False below is a one-off backfill value
    # only, required because assignment/shiftsignup are non-nullable FKs --
    # it's never actually applied since 0023 already deleted every row in
    # both tables.

    dependencies = [
        ('api', '0023_clear_pre_oppgaveslot_signups'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shiftsignup',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='assignment',
            name='oppgave_slot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.oppgaveslot'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shiftsignup',
            name='oppgave_slot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='api.oppgaveslot'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='shiftsignup',
            unique_together={('oppgave_slot', 'user')},
        ),
    ]
