# Generated by Django 5.2.5 on 2026-07-16 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_user_address_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='vakt_number',
            field=models.PositiveIntegerField(blank=True, help_text="The vakt's number, if it's one of the main numbered vakter (e.g. 5 for 'Vakt 5') -- used for the X1 vaktleder eligibility rule (>=2 of vakt 5-10). Blank for non-numbered vakter (lettered prep/teardown ones, etc.).", null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, help_text="Freeform 'tell us about yourself' from signup."),
        ),
        migrations.CreateModel(
            name='X1Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='x1_signups', to='api.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='x1_signups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('event', 'user')},
            },
        ),
    ]
