"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Set DJANGO_SECRET_KEY in the environment for any real deployment --
# this fallback is fine for local dev only.
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-local-dev-only-juDGHg7sPVY-vRWtti8agueyOsxIQvr6hveYTpZqAUeWMUWe6LSXwqyppEcbCP2588M",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "True") == "True"

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "*").split(",")

AUTH_USER_MODEL = "api.User"

# Email backend (first) handles login by email; ModelBackend (fallback)
# keeps the Django admin's username-based login working.
AUTHENTICATION_BACKENDS = [
    "api.auth_backends.EmailBackend",
    "django.contrib.auth.backends.ModelBackend",
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "rest_framework",   # add DRF
    "rest_framework_simplejwt.token_blacklist",  # lets a session be revoked, not just expire on its own
    "api",              # your custom API app
    'corsheaders',
]
# REST Framework configuration
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    # Per-IP limits on the sensitive unauthenticated endpoints -- see
    # api.throttling. Not a DEFAULT_THROTTLE_CLASSES entry, since the rest
    # of the API is already behind IsAuthenticated and doesn't need this.
    "DEFAULT_THROTTLE_RATES": {
        "register": "10/hour",
        "login": "20/hour",
        "password_setup_request": "5/hour",
        "password_setup_confirm": "20/hour",
    },
}

# The event runs many consecutive days, so a short-lived session that
# forces a daily re-login (djangorestframework-simplejwt's own defaults are
# 5 minutes access / 1 day refresh) would be actively hostile to volunteers
# mid-event. Rotating + blacklisting refresh tokens on every use means a
# stolen/replayed one is caught the next time the legitimate device tries
# to refresh, and -- combined with the token_blacklist app -- lets a
# specific person's session actually be revoked (see
# views.EventViewSet.remove_membership) instead of only ever expiring on
# its own.
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=14),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

# Set DJANGO_CORS_ALLOW_ALL=False and DJANGO_CORS_ALLOWED_ORIGINS (comma-
# separated) for a real deployment -- wide open is fine for local dev only.
CORS_ALLOW_ALL_ORIGINS = os.environ.get("DJANGO_CORS_ALLOW_ALL", "True") == "True"
if not CORS_ALLOW_ALL_ORIGINS:
    CORS_ALLOWED_ORIGINS = [
        origin.strip()
        for origin in os.environ.get("DJANGO_CORS_ALLOWED_ORIGINS", "").split(",")
        if origin.strip()
    ]
# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Set DATABASE_URL (e.g. a Supabase Postgres connection string) for any
# real deployment. Falls back to local SQLite when unset, blank, or
# whitespace-only -- os.environ.get's `default` param only kicks in when the
# key is absent, not when it's present as '' or ' ' (both of which
# dj_database_url can't parse: ValueError: No support for '').
_database_url = (os.environ.get("DATABASE_URL") or "").strip() or f"sqlite:///{BASE_DIR / 'db.sqlite3'}"
DATABASES = {
    'default': dj_database_url.parse(_database_url, conn_max_age=600)
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Resend (email) -- used for admin/staff invite emails. RESEND_API_KEY unset
# means invite emails are skipped (logged instead), so local dev/tests don't
# need a real key. RESEND_FROM_EMAIL must be on a domain verified in Resend.
#
# `or` rather than dict.get(key, default): a platform env var that's been
# added but left blank (present with value "") still satisfies .get()'s
# "key exists" check, silently overriding the default with "" instead of
# falling back to it -- which sent mail with an empty From address and no
# indication why. `or` treats blank the same as unset.
RESEND_API_KEY = os.environ.get("RESEND_API_KEY") or ""
RESEND_FROM_EMAIL = os.environ.get("RESEND_FROM_EMAIL") or "Hennings Alternativ Jul <onboarding@resend.dev>"

# Base URL of the admin dashboard for this environment, used to build the
# link in invite emails. Differs between preprod/prod, so it's env-driven
# like DJANGO_CORS_ALLOWED_ORIGINS rather than hardcoded.
ADMIN_DASHBOARD_URL = os.environ.get("ADMIN_DASHBOARD_URL", "http://localhost:5173")

# Base URL of the public website, used to build the link in password-setup
# emails (see email.send_password_setup_email). Differs between
# preprod/prod, same reasoning as ADMIN_DASHBOARD_URL.
WEBSITE_URL = os.environ.get("WEBSITE_URL", "http://localhost:4173")
